/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunerRouteImport } from './routes/tuner'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RiffsRouteImport } from './routes/riffs'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as JamRouteImport } from './routes/jam'
import { Route as ChordsRouteImport } from './routes/chords'
import { Route as IndexRouteImport } from './routes/index'

const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RiffsRoute = RiffsRouteImport.update({
  id: '/riffs',
  path: '/riffs',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const JamRoute = JamRouteImport.update({
  id: '/jam',
  path: '/jam',
  getParentRoute: () => rootRouteImport,
} as any)
const ChordsRoute = ChordsRouteImport.update({
  id: '/chords',
  path: '/chords',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chords': typeof ChordsRoute
  '/jam': typeof JamRoute
  '/notes': typeof NotesRoute
  '/riffs': typeof RiffsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tuner': typeof TunerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chords': typeof ChordsRoute
  '/jam': typeof JamRoute
  '/notes': typeof NotesRoute
  '/riffs': typeof RiffsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tuner': typeof TunerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chords': typeof ChordsRoute
  '/jam': typeof JamRoute
  '/notes': typeof NotesRoute
  '/riffs': typeof RiffsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tuner': typeof TunerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chords'
    | '/jam'
    | '/notes'
    | '/riffs'
    | '/sitemap.xml'
    | '/tuner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chords' | '/jam' | '/notes' | '/riffs' | '/sitemap.xml' | '/tuner'
  id:
    | '__root__'
    | '/'
    | '/chords'
    | '/jam'
    | '/notes'
    | '/riffs'
    | '/sitemap.xml'
    | '/tuner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChordsRoute: typeof ChordsRoute
  JamRoute: typeof JamRoute
  NotesRoute: typeof NotesRoute
  RiffsRoute: typeof RiffsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TunerRoute: typeof TunerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riffs': {
      id: '/riffs'
      path: '/riffs'
      fullPath: '/riffs'
      preLoaderRoute: typeof RiffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jam': {
      id: '/jam'
      path: '/jam'
      fullPath: '/jam'
      preLoaderRoute: typeof JamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chords': {
      id: '/chords'
      path: '/chords'
      fullPath: '/chords'
      preLoaderRoute: typeof ChordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChordsRoute: ChordsRoute,
  JamRoute: JamRoute,
  NotesRoute: NotesRoute,
  RiffsRoute: RiffsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TunerRoute: TunerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
